### ISSUE TITLE
Unable to build windows release. velopack_flutter_cargokit.rule' exited with code -1

### ISSUE THREAD

**Issue by rlbjorn** [GigaDroid/velopack_flutter#2]
Error when building windows release on clean project. 
velopack_flutter version:   velopack_flutter: ^0.1.0

Error output:
`C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'C:\gitrepos\raven_app_flutter\build\windows\x64\CMakeFiles\07cdbba094bbd14e85df852bffc13caf\velopack_flutter.dll.rule;C:\gitrepos\raven_app_flutter\build\windows\x64\CMakeFiles\64e0a3eb41a4a85df7d672f0ced65dec\velopack_flutter_cargokit.rule' exited with code -1. [C:\gitrepos\raven_app_flutter\build\windows\x64\plugins\velopack_flutter\velopack_flutter_cargokit.vcxproj]`

Thanks a lot for starting the work on this package btw!

**Comment by GigaDroid** [comment]
Thank you! Just to make sure, do you have rust installed on your system?

**Comment by rlbjorn** [comment]
I do not. Im sensing a very rookie mistake on my part. I will install rust, recheck and resolve the issue if its fixed.

**Comment by GigaDroid** [comment]
@rlbjorn can this be closed?
